workflows:
  android-apk:
    name: Android APK (release)
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - manual
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Flutter doctor
        script: flutter doctor -v
      - name: Get packages
        script: flutter pub get
      - name: Ensure Android platform exists
        script: |
          if [ ! -d "android" ]; then
            echo "android/ not found -> generating with flutter create ."
            flutter create .
          fi
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
